Posts Feature + EditForm Component added
octoco-ltd/octoco-templates pull request #10
Opened 2024-02-07 13:40 UTC by Alfred-Octoco

Added functionality to allow the viewing/editing/deleting of a users posts

2024-02-07 13:43 UTC, Alfred-Octoco commented
There is new functionality added to the page when selecting a user from home on the table of users that allows for the viewing of posts. As well as editing and deleting the posts

Some concerns about dependencies that where updated

2024-02-09 07:56 UTC, OctoPikkie requested changes

2024-02-09 07:56 UTC, OctoPikkie commented on templates/ts-react-app/src/components/dialogs/EditDialog.tsx
> +import { Dialog, DialogTitle, DialogContent, TextField, DialogActions, Button } from '@mui/material';
I like the idea of a generic dialog popup. However, being generic it should be able to cater for more situations than just "TextField". 

When writing a generic, I would say it is better to create it in a way that receives the form component and renders is. (It might handle the title on its own, receive onCancel and onAccept function to run as point of actions), but this way you can throw any content into the re-usable dialog.

2024-02-09 07:56 UTC, OctoPikkie commented on templates/ts-react-app/src/features/posts/components/listPosts/ListPosts.tsx
> +    useGetAllPostsByUserQuery(userId ?? '5');
We would not always want 5 to be called if the id is undefined. We would either want to return that userID was not found by returning an error component before this is defined. Or alternatively, use a lazy query to only do the API call once there is infact a userId

2024-02-09 07:56 UTC, OctoPikkie commented on templates/ts-react-app/src/features/posts/components/listPosts/ListPosts.tsx
> +      flex: 1,
mui-data-grid has an nifty "actions" type for a column which helps you define all row actions neatly.

Might be considered here.

For Example:
```
{
  field: 'actions',
  type: 'actions',
  getActions: (params: GridRowParams) => [
    <GridActionsCellItem icon={...} onClick={...} label="Delete" />,
    <GridActionsCellItem icon={...} onClick={...} label="Print" showInMenu />,
  ]
}
```

2024-05-06 07:05 UTC, closed without merging